# Generated by Django 3.2 on 2023-04-06 21:56

import accounts.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_hospital', models.BooleanField(default=False, verbose_name='Is Hospital')),
                ('role', models.CharField(choices=[('Doctor', 'doctor'), ('Patient', 'patient')], max_length=50, verbose_name='Role')),
                ('Phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=50, verbose_name='Specialist')),
                ('cv', models.FileField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='CV')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Certificate')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Profile Photo')),
                ('exp', models.IntegerField(blank=True, null=True, verbose_name='Doctor Experience')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Doctor Fee')),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to=accounts.models.patient_dir_path, verbose_name='Profile Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_Patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('country_address', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('Address', models.CharField(max_length=50, verbose_name='Address')),
                ('image', models.ImageField(upload_to=accounts.models.hospital_dir_path, verbose_name='Image')),
                ('model', models.CharField(choices=[('Hospital', 'hospital'), ('Center', 'center')], max_length=50, verbose_name='Model')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Fee')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
        ),
    ]
