# Generated by Django 3.2 on 2023-03-21 00:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_doctor_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='exp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Doctor Experience'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Doctor price'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to=accounts.models.patient_dir_path, verbose_name='Profile Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
