# Generated by Django 3.2 on 2023-03-21 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230321_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rate'),
        ),
    ]
