# Generated by Django 3.2 on 2023-03-21 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230321_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to='accounts.review', verbose_name='Review'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to='accounts.doctor', verbose_name='Doctor'),
        ),
    ]
