# Generated by Django 3.2 on 2023-03-22 22:10

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230322_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='admin',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin', to='accounts.user', verbose_name='Admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Fee'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='accounts.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Doctor Fee'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(upload_to=accounts.models.hospital_dir_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='model',
            field=models.CharField(choices=[('Hospital', 'hospital'), ('Center', 'center')], max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
