# Generated by Django 3.2 on 2023-03-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230323_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='price',
            new_name='fee',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='accounts.review', verbose_name='Review'),
        ),
    ]
