# Generated by Django 3.2 on 2023-03-22 22:40

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_review_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to='accounts.review', verbose_name='Review'),
        ),
    ]
