# Generated by Django 3.2 on 2023-03-23 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230323_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='review',
            name='patient',
        ),
    ]
