# Generated by Django 3.2 on 2023-03-23 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('accounts', '0012_auto_20230324_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to='consultation.review', verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='consultation.review', verbose_name='Review'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
