# Generated by Django 3.2 on 2023-04-06 21:56

import consultation.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Questions Category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Patient Name')),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Age')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True, verbose_name='Gender')),
                ('mri', models.FileField(upload_to=consultation.models.patient_dir_path, verbose_name='MRI')),
                ('ct', models.FileField(upload_to=consultation.models.patient_dir_path, verbose_name='CT')),
                ('ecg', models.FileField(upload_to=consultation.models.patient_dir_path, verbose_name='ECG')),
                ('title', models.CharField(max_length=200, verbose_name='Tiltle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('review', models.TextField(max_length=500, verbose_name='Review')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to='accounts.doctor', verbose_name='Doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_reviews', to='accounts.hospital', verbose_name='Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejeted')], default='pending', max_length=50, verbose_name='Status')),
                ('accepted_hospitals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_H_consultation_requests', to='accounts.doctor')),
                ('doctors', models.ManyToManyField(blank=True, related_name='Hospital_survey_request', to='accounts.Hospital')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.survey')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejeted')], default='pending', max_length=50, verbose_name='Status')),
                ('accepted_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_D_consultation_requests', to='accounts.doctor')),
                ('doctors', models.ManyToManyField(blank=True, related_name='doctors_survey_request', to='accounts.Doctor')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=20)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consultation.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_ans', to='consultation.survey', verbose_name='Survey')),
            ],
        ),
    ]
