# Generated by Django 3.2 on 2023-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='question_1',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_10',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='10'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_11',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='11'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_2',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='2'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_3',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='3'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_4',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='4'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_5',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='5'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_6',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='6'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_7',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='7'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_8',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='8'),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_9',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=50, null=True, verbose_name='9'),
        ),
        migrations.AlterField(
            model_name='doctorconsultationrequest',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
