# Generated by Django 3.2 on 2023-03-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230324_0124'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True/False'), ('SA', 'Short Answer')], max_length=3)),
                ('question_text', models.TextField(verbose_name='Question')),
                ('answer_text', models.TextField()),
                ('category', models.CharField(max_length=50, verbose_name='Questions Category')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to='accounts.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_reviews', to='accounts.hospital', verbose_name='Hospital'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mri', models.FileField(upload_to=None, verbose_name='MRI Scan')),
                ('ct', models.FileField(upload_to=None, verbose_name='CT-Scan')),
                ('ecg', models.FileField(upload_to=None, verbose_name='ECG')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed', models.BooleanField(default=False)),
                ('doctor', models.ManyToManyField(blank=True, null=True, related_name='doctors_survey', to='accounts.Doctor')),
                ('hospital', models.ManyToManyField(blank=True, null=True, related_name='hospitals_survey', to='accounts.Hospital', verbose_name='Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('questions', models.ManyToManyField(related_name='survey_questions', to='consultation.Question', verbose_name='Questions')),
            ],
        ),
    ]
