# Generated by Django 3.2 on 2023-03-24 21:49

import consultation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_auto_20230324_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=1, verbose_name='patient Answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='ct',
            field=models.FileField(upload_to=consultation.models.patient_dir_path, verbose_name='CT'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ecg',
            field=models.FileField(upload_to=consultation.models.patient_dir_path, verbose_name='ECG'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mri',
            field=models.FileField(upload_to=consultation.models.patient_dir_path, verbose_name='MRI'),
        ),
    ]
