# Generated by Django 3.2 on 2023-03-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_auto_20230325_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tiltle'),
        ),
    ]
