# Generated by Django 3.2 on 2023-04-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='patient',
        ),
    ]
