# Generated by Django 3.2 on 2023-03-24 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230324_0124'),
        ('consultation', '0005_auto_20230325_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='hospital',
        ),
        migrations.CreateModel(
            name='HospitalConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('accepted_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_H_consultation_requests', to='accounts.doctor')),
                ('doctors', models.ManyToManyField(blank=True, related_name='Hospital_survey_request', to='accounts.Hospital')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.survey')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('accepted_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_D_consultation_requests', to='accounts.doctor')),
                ('doctors', models.ManyToManyField(blank=True, related_name='doctors_survey_request', to='accounts.Doctor')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultation.survey')),
            ],
        ),
    ]
