# Generated by Django 3.2 on 2023-04-23 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_remove_report_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_diagnosis', models.CharField(max_length=50)),
                ('mri_diagnosis', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_survey', to='consultation.survey')),
            ],
        ),
    ]
