# Generated by Django 3.2 on 2023-03-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_auto_20230325_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "Don't Know")], max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.question')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='answers',
            field=models.ManyToManyField(to='consultation.Answer', verbose_name='survey_answers'),
        ),
    ]
