# Generated by Django 3.2 on 2023-04-26 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_auto_20230425_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_request', to='consultation.survey'),
        ),
    ]
