# Generated by Django 3.2 on 2023-03-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_auto_20230327_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Questions Category'),
        ),
    ]
