# Generated by Django 3.2 on 2023-03-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_alter_survey_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
    ]
