# Generated by Django 3.2 on 2023-05-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('consultation', '0011_alter_consultation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctors',
            field=models.ManyToManyField(related_name='consultations_hospital', to='accounts.Hospital'),
        ),
    ]
