# Generated by Django 3.2 on 2023-03-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_remove_survey_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='age',
        ),
        migrations.AddField(
            model_name='survey',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
