# Generated by Django 3.2 on 2023-03-27 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_auto_20230327_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(related_name='survey_questions', to='consultation.Question', verbose_name='Questions'),
        ),
    ]
