# Generated by Django 3.2 on 2023-05-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('consultation', '0013_auto_20230526_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctors',
            field=models.ManyToManyField(blank=True, null=True, related_name='consultations_doctor', to='accounts.Doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='hospital',
            field=models.ManyToManyField(blank=True, null=True, related_name='consultations_hospital', to='accounts.Hospital'),
        ),
    ]
