# Generated by Django 3.2 on 2023-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0014_auto_20230327_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ManyToManyField(related_name='survey_ans', to='consultation.Survey', verbose_name='Survey'),
        ),
    ]
