# Generated by Django 3.2 on 2023-03-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0015_answer_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(related_name='survey_questions', to='consultation.Survey', verbose_name='Survey'),
        ),
    ]
