# Generated by Django 3.2 on 2023-03-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0016_auto_20230327_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ManyToManyField(related_name='survey_ans', to='consultation.Survey', verbose_name='Survey'),
        ),
    ]
