# Generated by Django 3.2 on 2023-03-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0018_alter_survey_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
